### ISSUE TITLE
License in package.json

### ISSUE THREAD

**Issue by szaffarano** [stream-utils/pause#10]
I'm using [pkg](https://github.com/zeit/pkg/) to build my project, and I need that all the package.json files of my dependencies have a licensing attribute.  Please, can you add a license entry in your project?
Thank you

**Comment by dougwilson** [comment]
Isn't it already there? What do I need to?

**Comment by dougwilson** [comment]
Here is what is currently in package.json:

      "license": "MIT",

**Comment by szaffarano** [comment]
I'm sorry, it was my mistake.  Pause is a transitive dependency in my project, Today I've searched by name, and I found your project.  The real dependency that I need the license change is [node-pause](https://github.com/mikermcneil/node-pause).
Thank you for your time.

**Comment by dougwilson** [comment]
It's no problem at all. Let me know (or even feel free to make a pull request) if you need anything changed in the future :+1:
